# AQI預測系統 - 模型配置
# Model Configurations for AQI Prediction System

# LightGBM配置
lightgbm:
  # 基本參數
  objective: "regression"
  metric: "mae"
  boosting_type: "gbdt"
  
  # 樹結構參數
  num_leaves: 31
  max_depth: 8
  min_data_in_leaf: 100
  
  # 學習參數
  learning_rate: 0.1
  n_estimators: 1000
  
  # 特徵選擇參數
  feature_fraction: 0.8
  bagging_fraction: 0.8
  bagging_freq: 5
  
  # 正則化參數
  lambda_l1: 0.0
  lambda_l2: 0.0
  
  # 其他參數
  verbose: -1
  max_bin: 511
  force_col_wise: true
  early_stopping_rounds: 100
  random_state: 42
  
  # 交叉驗證參數
  cv_folds: 5
  cv_stratified: false

# LSTM配置
lstm:
  # 模型架構
  architecture:
    hidden_size: 128
    num_layers: 3
    dropout: 0.2
    bidirectional: false
  
  # 訓練參數
  training:
    learning_rate: 0.001
    batch_size: 128
    epochs: 100
    early_stopping_patience: 10
    
  # 優化器參數
  optimizer:
    type: "Adam"
    weight_decay: 0.00001
    betas: [0.9, 0.999]
    eps: 0.00000001
  
  # 學習率調度器
  scheduler:
    type: "StepLR"
    step_size: 20
    gamma: 0.5
    patience: 5
  
  # 正則化
  regularization:
    grad_clip: 1.0
    dropout: 0.2
    layer_norm: false
  
  # 其他參數
  random_state: 42
  pin_memory: true

# 模型選擇策略
model_selection:
  # 交叉驗證策略
  cv_strategy: "time_series"  # time_series, k_fold, stratified
  cv_folds: 5
  
  # 評估策略
  evaluation_strategy:
    primary_metric: "mae"
    secondary_metrics: ["rmse", "mape", "r2"]
    minimize: true  # true for mae/rmse/mape, false for r2
  
  # 超參數調優
  hyperparameter_tuning:
    method: "random_search"  # grid_search, random_search, bayesian
    n_trials: 50
    timeout: 3600  # 秒
  
  # 模型集成
  ensemble:
    enable: false
    methods: ["voting", "stacking", "blending"]
    weights: "auto"

# 特徵工程配置
feature_engineering:
  # 時間特徵
  time_features:
    enable: true
    features: ["hour", "day_of_week", "month", "season"]
    cyclical_encoding: true
  
  # 滯後特徵
  lag_features:
    enable: true
    lags: [1, 3, 6, 12, 24]
    targets_only: false
  
  # 滾動統計特徵
  rolling_features:
    enable: true
    windows: [3, 6, 12, 24]
    statistics: ["mean", "std", "min", "max"]
  
  # 差分特徵
  diff_features:
    enable: true
    orders: [1, 2]
    seasonal: [24, 168]  # 日週期、週週期

# 數據預處理配置
preprocessing:
  # 缺失值處理
  missing_values:
    strategy: "interpolation"  # drop, mean, median, interpolation, forward_fill
    interpolation_method: "linear"
    max_consecutive_missing: 6
  
  # 異常值處理
  outliers:
    detection_method: "iqr"  # iqr, zscore, isolation_forest
    treatment: "clip"  # remove, clip, transform
    threshold: 3.0
  
  # 數據標準化
  scaling:
    method: "standard"  # standard, minmax, robust, quantile
    feature_range: [0, 1]  # for minmax scaling
  
  # 數據平衡
  balancing:
    enable: false
    method: "smote"  # smote, adasyn, random_oversample
    ratio: "auto" 