# combine_norm模式配置
# Pipeline Configuration for Combine Normalization Mode

pipeline:
  name: "combine_norm"
  description: "合併所有測站的標準化數據進行統一訓練"
  type: "global"
  
# 數據源配置
data_source:
  raw_dir: "data/raw/Combine_Nomolization"
  file_pattern: "*_combined.csv"
  combine_strategy: "concatenate"
  station_encoding: true  # 是否添加測站編碼特徵

# 預處理配置
preprocessing:
  normalization: true  # 數據已經標準化
  station_specific: false
  feature_selection:
    method: "correlation"  # correlation, importance, variance
    threshold: 0.95
  
# 輸出路徑配置
output_paths:
  processed_data: "data/processed/combine_norm"
  windows_data: "data/windows/combine_norm"
  models: 
    lightgbm: "models/lightgbm/combine_norm"
    lstm: "models/lstm/combine_norm"
  reports: "outputs/reports/combine_norm"
  predictions: "outputs/predictions"
  evaluations: "outputs/evaluations"

# 訓練配置
training:
  cross_validation: true
  validation_strategy: "time_series_split"
  test_size: 0.1
  
# 特殊參數
special_config:
  multi_station_features: true
  station_weights: "equal"  # equal, population, area
  spatial_features: false
  temporal_alignment: true
  normalized_input: true
  
# 批量處理配置
batch_processing:
  parallel: false  # 全域模式通常單進程
  max_workers: 1 